# Generated by Django 4.0.5 on 2022-07-08 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятница'), ('СБ', 'Суббота'), ('ВС', 'Воскресенье')], max_length=30, verbose_name='День недели')),
                ('timetb', models.TimeField(verbose_name='Время')),
                ('duration', models.IntegerField(default=2, verbose_name='Длительность')),
                ('id_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.branch', verbose_name='Филиал')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.course', verbose_name='Предмет')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Расписание',
                'ordering': ['id_teacher', 'id_course', 'id_branch', 'day_of_week', 'timetb'],
            },
        ),
    ]
