# Generated by Django 4.0.5 on 2022-07-08 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0002_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateTimeField(verbose_name='Дата')),
                ('number_hours', models.IntegerField(default=2, verbose_name='Количество часов')),
                ('ispaid', models.BooleanField(default=False)),
                ('id_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.branch', verbose_name='Филиал')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.course', verbose_name='Предмет')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Рабочие часы',
                'verbose_name_plural': 'Рабочие часы',
                'ordering': ['date_of_visit', 'id_teacher', '-ispaid'],
            },
        ),
    ]
