# Generated by Django 4.0.5 on 2022-07-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_teacherjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherjournal',
            name='time_of_visit',
            field=models.TimeField(default='15:00:00', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='teacherjournal',
            name='date_of_visit',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
