# Generated by Django 4.0.5 on 2022-07-17 15:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['surname'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterField(
            model_name='client',
            name='guardian',
            field=models.CharField(max_length=200, verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(max_length=60, verbose_name='Фамилия'),
        ),
        migrations.CreateModel(
            name='Paying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('summ', models.IntegerField(verbose_name='Сумма')),
                ('subscription', models.IntegerField(default=1, verbose_name='Количество занятий')),
                ('id_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.branch', verbose_name='Филиал')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.client', verbose_name='Ученик')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.course', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
                'ordering': ['date'],
            },
        ),
    ]
