# Generated by Django 4.0.5 on 2022-07-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_visitfix_options_client_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['active', 'surname'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=2, verbose_name='Длительность'),
        ),
    ]
