# Generated by Django 4.0.5 on 2022-07-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_alter_visitfix_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitfix',
            name='payed',
            field=models.ForeignKey(null=True, on_delete=models.SET(False), to='journal.paying', verbose_name='Дата оплаты'),
        ),
    ]
