# Generated by Django 4.1.4 on 2023-04-28 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_client_address_client_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
    ]
