# Generated by Django 4.2.1 on 2023-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0021_alter_teacher_options_alter_salary_id_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tg_name',
            field=models.CharField(default='unknown', max_length=150, verbose_name='Имя Telegram'),
        ),
    ]
