# Generated by Django 4.2.1 on 2023-06-04 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_alter_teacher_tg_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='id_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.teacher', verbose_name='Преподаватель'),
        ),
    ]
