# Generated by Django 4.2.1 on 2023-06-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_alter_timetable_id_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tg_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tg_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tg_name',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Имя Telegram'),
        ),
    ]
