# Generated by Django 4.2.1 on 2023-06-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_client_tg_id_alter_teacher_tg_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tg_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Имя Telegram'),
        ),
    ]
