# Generated by Django 4.2.1 on 2023-06-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_alter_teacher_tg_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitfix',
            name='payed',
        ),
        migrations.AddField(
            model_name='paying',
            name='used_lesson',
            field=models.IntegerField(default=0, verbose_name='Использовано'),
        ),
    ]
