# Generated by Django 4.2.1 on 2023-07-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0028_salary_date_of_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=10, verbose_name='Номер')),
                ('metka', models.CharField(blank=True, max_length=3, null=True, verbose_name='Метка')),
                ('manufacture', models.CharField(max_length=20, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=20, null=True, verbose_name='Модель')),
                ('os', models.CharField(max_length=60, verbose_name='Операционная система')),
                ('cpu', models.CharField(max_length=30, verbose_name='Процессор')),
                ('cpu_mark', models.CharField(blank=True, max_length=30, null=True, verbose_name='Модель процессора')),
                ('cpu_hash', models.CharField(blank=True, max_length=10, null=True, verbose_name='Кеш памяти')),
                ('cpu_takt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тактовая частота')),
                ('cpu_shin', models.CharField(blank=True, max_length=20, null=True, verbose_name='Частота шины')),
                ('ozu', models.CharField(max_length=60, verbose_name='Оперативная память')),
                ('hdd_sdd', models.CharField(max_length=120, verbose_name='Диски')),
                ('note', models.CharField(blank=True, max_length=60, null=True, verbose_name='Состояние')),
                ('date_start', models.DateField(verbose_name='Дата покупки/начала эксплуатации')),
                ('data_service', models.DateField(verbose_name='Последнее обслуживание')),
                ('id_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
                'ordering': ['manufacture', 'id_branch'],
            },
        ),
    ]
