# Generated by Django 4.2.1 on 2023-07-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0029_computers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='hdd_sdd',
            field=models.CharField(max_length=160, verbose_name='Диски'),
        ),
    ]
