# Generated by Django 4.2.1 on 2023-10-13 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0030_alter_computers_hdd_sdd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computers',
            name='cpu_hash',
        ),
        migrations.RemoveField(
            model_name='computers',
            name='cpu_mark',
        ),
        migrations.RemoveField(
            model_name='computers',
            name='cpu_shin',
        ),
        migrations.RemoveField(
            model_name='computers',
            name='cpu_takt',
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона введен некорректный', regex='^7([0-9]){9}[0-9]$')], verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='cpu',
            field=models.CharField(max_length=150, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='os',
            field=models.CharField(max_length=250, verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Номер телефона введен некорректный', regex='^7([0-9]){9}[0-9]$')], verbose_name='Номер телефона'),
        ),
    ]
