# Generated by Django 4.2.1 on 2023-12-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0031_remove_computers_cpu_hash_remove_computers_cpu_mark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollTgbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.CharField(max_length=30)),
                ('options', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='tg_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
