# Generated by Django 4.2.1 on 2023-12-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0032_polltgbot_timetable_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tg_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
