version: '3.8'

# хранилища
volumes:
    pgdata:
        driver: local
        name: pgdata
services:
    cyb_postgres:
        image: postgres:15
        container_name: cyb_postgres
        env_file:
          - .env  
        volumes:
            - pgdata:/var/lib/postgresql/data
    python:
        restart: always
# указываем откуда собирать образ
        build:
          context: .
          dockerfile: Dockerfile
# монтируем директорию проекта
        volumes:
          - .:/usr/src/cybcrm
        expose:
          - 8000
        ports:
          - 8000:8000
        env_file:
          - .env
        depends_on:
          - cyb_postgres
          
# запускаем gunicorn
        # command: "gunicorn -c gunicorn.py cybcrm.wsgi"
    nginx:
        restart: always
        image: nginx:latest
        expose:
          - 8080
        ports:
          - "80:8080"
        volumes:
            - ./static:/usr/src/cybcrm/static
            - ./logs:/usr/src/cybcrm/logs
# и nginx зависит от контейнера python. Т.е. python должен быть запущен первым
        depends_on:
            - python

